import Vue from "vue";
declare const _default: import("vue/types/vue").ExtendedVue<Vue, {
    element: HTMLDivElement;
    pos1: number;
    pos2: number;
    pos3: number;
    pos4: number;
    _bottom: number;
    _left: number;
    _right: number;
    _top: number;
    rect: DOMRect;
    resizing: boolean;
    resizeHandle: string;
    initialRect: DOMRect | null;
    coords: string[];
    isFullScreen: Boolean;
}, {
    closeDragElement(): void;
    elementDrag(e: MouseEvent): void;
    elementMobileDrag(e: TouchEvent): void;
    dragMouseDown(e: MouseEvent): void;
    dragElement(elmnt: HTMLDivElement): void;
    closePopup(): void;
    toggleFullscreen(): void;
    resizeMouseDown(event: MouseEvent, handle: "top-left" | "top-right" | "bottom-left" | "bottom-right"): void;
    resizeMouseMove(event: any): void;
    resizeMouseUp(): void;
    clickEvent(e: Event): void;
    fixZIndex(): void;
    configureForEditor(): void;
}, unknown, {
    width: string;
    height: string;
    headerPadding: string;
    right: string;
    left: string;
    top: string;
    bottom: string;
    zIndex: string;
    pinned: boolean;
    backgroundColor: string;
    _renderingProps: any;
    class: string;
    border: boolean;
    closeBtn: boolean;
    fullScreen: boolean;
    resizable: boolean;
}>;
export default _default;
//# sourceMappingURL=QLightBox.vue.d.ts.map